# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactStarter

  # target 'reactStarter-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'reactStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'reactStarter-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for reactStarter-tvOS

#   target 'reactStarter-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
